#!/usr/bin/env php
<?php

(@include_once __DIR__ . '/vendor/autoload.php') || @include_once __DIR__ . '/../../autoload.php';

$samurai = new \Samurai\Samurai(new \Symfony\Component\Console\Application());
$samurai->run(); //banzai!
