#!/usr/bin/env php
<?php

(@include_once __DIR__ . '/vendor/autoload.php') || @include_once __DIR__ . '/../../autoload.php';

set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__);

$samurai = new \Samurai\Samurai(new \Symfony\Component\Console\Application());
$samurai->run(); //banzai!
