<?php
namespace Samurai\Command;

use Pimple\Container;
use Puppy\Config\Config;
use Samurai\Alias\AliasManager;
use Samurai\Composer\Project;
use Samurai\Samurai;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ChoiceQuestion;
use Symfony\Component\Console\Tester\CommandTester;

class GenerateTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     */
    public function testDefault()
    {

        $executor = $this->getMock('TRex\Cli\executor');
        $executor->expects($this->any())
            ->method('flush')
            ->will($this->returnValue(true));

        $questionHelper = $this->getMock('Symfony\Component\Console\Helper\QuestionHelper', array('ask'));

        $questionHelper->expects($this->at(0))
            ->method('ask')
            ->will($this->returnCallback(function(InputInterface $input, OutputInterface $output, ChoiceQuestion $question){
                $choices = $question->getChoices();
                return current($choices);
            }));

        $questionHelper->expects($this->at(1))
            ->method('ask')
            ->will($this->returnValue('vendor/package'));


        $application = new Application();
        $samurai = new Samurai($application, $this->provideServices($questionHelper), $executor);

        $command = $application->find('new');
        $command->getHelperSet()->set($questionHelper, 'question');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName()
        ]);

        $this->assertRegExp('/Installing project vendor\/package from raphhh\/php-lib-bootstrap/', $commandTester->getDisplay());
        $this->assertRegExp('/Initializing composer config/', $commandTester->getDisplay());
        $this->assertRegExp('/Generated by Samurai in \d+\.\d{2} sec. Banzai!/', $commandTester->getDisplay());

        /**
         * @var Project $project
         */
        $project = $samurai->getServices()['composer']->getProject();
        $this->assertSame('vendor/package', $project->getName());
        $this->assertSame('raphhh/php-lib-bootstrap', $project->getBootstrapName());
        $this->assertSame('', $project->getBootstrapVersion());
        $this->assertSame('vendor/package', $project->getDirectoryPath());
        $this->assertSame('', $project->getDescription());
        $this->assertSame('', $project->getHomepage());
        $this->assertSame([], $project->getKeywords());
    }

    public function testFilled()
    {
        $executor = $this->getMock('TRex\Cli\executor');
        $executor->expects($this->any())
            ->method('flush')
            ->will($this->returnValue(true));

        $questionHelper = $this->getMock('Symfony\Component\Console\Helper\QuestionHelper', array('ask'));

        $questionHelper->expects($this->at(0))
            ->method('ask')
            ->will($this->returnValue('vendor/package'));

        $questionHelper->expects($this->at(1))
            ->method('ask')
            ->will($this->returnValue('desc'));

        $questionHelper->expects($this->at(2))
            ->method('ask')
            ->will($this->returnValue('http://website.com'));

        $questionHelper->expects($this->at(3))
            ->method('ask')
            ->will($this->returnValue(' k1 , k2'));


        $application = new Application();
        $samurai = new Samurai($application, $this->provideServices($questionHelper), $executor);

        $command = $application->find('new');
        $command->getHelperSet()->set($questionHelper, 'question');

        $commandTester = new CommandTester($command);
        $commandTester->execute([
            'command' => $command->getName(),
            'bootstrap' => 'vendor/bootstrap',
            'version' => '1.0.0',
            '--dir' => 'dir/path',
            '--repo' => 'repo',
        ]);

        $this->assertRegExp('/Installing project vendor\/package from vendor\/bootstrap/', $commandTester->getDisplay());
        $this->assertRegExp('/Initializing composer config/', $commandTester->getDisplay());
        $this->assertRegExp('/Generated by Samurai in \d+\.\d{2} sec. Banzai!/', $commandTester->getDisplay());

        /**
         * @var Project $project
         */
        $project = $samurai->getServices()['composer']->getProject();
        $this->assertSame('vendor/package', $project->getName());
        $this->assertSame('vendor/bootstrap', $project->getBootstrapName());
        $this->assertSame('1.0.0', $project->getBootstrapVersion());
        $this->assertSame('dir/path', $project->getDirectoryPath());
        $this->assertSame('desc', $project->getDescription());
        $this->assertSame('http://website.com', $project->getHomepage());
        $this->assertSame(['k1', 'k2'], $project->getKeywords());
    }

    /**
     * @param QuestionHelper $questionHelper
     * @return Container
     * @internal param $result
     */
    private function provideServices(QuestionHelper $questionHelper)
    {
        $composer = $this->provideComposer(true);

        $services = new Container();
        $services['composer'] = function () use ($composer) {
            return $composer;
        };
        $services['question'] = function () use ($questionHelper) {
            return $questionHelper;
        };

        $services['alias_manager'] = function () {
            return new AliasManager(new Config('', __DIR__ . '/../../config')); //todo
        };
        return $services;
    }

    private function provideComposer($result)
    {
        $composer = $this->getMockBuilder('Samurai\Composer\Composer')
            ->disableOriginalConstructor()
            ->getMock();

        $composer->expects($this->any())
            ->method('resetConfig');

        $composer->expects($this->any())
            ->method('validateConfig')
            ->will($this->returnValue($result));

        $composer->expects($this->any())
            ->method('createProject')
            ->will($this->returnValue($result));

        $composer->expects($this->any())
            ->method('getProject')
            ->will($this->returnValue(new Project()));

        return $composer;
    }


}
